spring.application.name=SpringJenkinsApplication


public WebClient getWebClient(){
 return webclient.builder().credentials();
}

public ResponseEntity<Customer> getCustomer(@RequestBody Customer cust){
    ResponseEntity<Customer> entity= webClient.url("https:/endpoint/").post(cust);
}